[theme]
base = "dark"
primaryColor = "#E50914"
backgroundColor = "#141414"
secondaryBackgroundColor = "#181818"
textColor = "#E5E5E5"
font = "Inter"

[server]
headless = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showSidebarNavigation = false
